
	MERGE [dm].[F_PURCHASES] trg
		USING [dm_prl].[F_PURCHASES_hist] src
		 ON [src].[Purchasing_Document_SK]								= [trg].[Purchasing_Document_SK]
		 And [src].[Purchasing_Document_Item_ID]							= [trg].[Purchasing_Document_Item_ID]		
		 And [src].[Account_Assignment_Sequential_ID]						= [trg].[Account_Assignment_Sequential_ID]	
		 And [src].[Purchase_Order_History_Transaction_Event_Type_ID]		= [trg].[Purchase_Order_History_Transaction_Event_Type_ID]		
		 And [src].[Material_Document_Year]								= [trg].[Material_Document_Year]	
		 And [src].[Material_Document_SK]									= [trg].[Material_Document_SK] 
		 And [src].[Material_Document_Item_ID]							= [trg].[Material_Document_Item_ID] 

	WHEN MATCHED THEN
	UPDATE SET 
			     [Purchasing_Document_SK]  =   SRC.[Purchasing_Document_SK]
                ,[Purchasing_Document_Item_ID]  =   SRC.[Purchasing_Document_Item_ID]
                ,[Account_Assignment_Sequential_ID]  =   SRC.[Account_Assignment_Sequential_ID]
                ,[Purchase_Order_History_Transaction_Event_Type_ID]  =   SRC.[Purchase_Order_History_Transaction_Event_Type_ID]
                ,[Material_Document_Year]  =   SRC.[Material_Document_Year]
                ,[Material_Document_SK]  =   SRC.[Material_Document_SK]
                ,[Material_Document_ID]  =   SRC.[Material_Document_ID]
                ,[Material_Document_Item_ID]  =   SRC.[Material_Document_Item_ID]
                ,[PostingDatekey]  =   SRC.[PostingDatekey]
                ,[Purchase_Order_History_Category_ID]  =   SRC.[Purchase_Order_History_Category_ID]
                ,[FinalQuantity]  =   SRC.[FinalQuantity]
                ,[FinalAmount]  =   SRC.[FinalAmount]
                ,[Material_SK]  =   SRC.[Material_SK]
                ,[Plant_SK]  =   SRC.[Plant_SK]
                ,[Vendor_SK]  =   SRC.[Vendor_SK]
                ,[Company_SK]  =   SRC.[Company_SK]
                ,[Sales_Organization_SK]  =   SRC.[Sales_Organization_SK]
                ,[DocumentDatekey]  =   SRC.[DocumentDatekey]
                ,[EntryDatekey]  =   SRC.[EntryDatekey]
                ,[Entry_TM]  =   SRC.[Entry_TM]
                ,[Inventory_Management_Movement_Type_ID]  =   SRC.[Inventory_Management_Movement_Type_ID]
                ,[ETL_Reference_DT]  =   SRC.[ETL_Reference_DT]
                ,[ETL_Batch_ID]  =   SRC.[ETL_Batch_ID]

	WHEN NOT MATCHED BY TARGET
	THEN INSERT (
		 [Purchasing_Document_SK]
        ,[Purchasing_Document_Item_ID]
        ,[Account_Assignment_Sequential_ID]
        ,[Purchase_Order_History_Transaction_Event_Type_ID]
        ,[Material_Document_Year]
        ,[Material_Document_SK]
        ,[Material_Document_ID]
        ,[Material_Document_Item_ID]
        ,[PostingDatekey]
        ,[Purchase_Order_History_Category_ID]
        ,[FinalQuantity]
        ,[FinalAmount]
        ,[Material_SK]
        ,[Plant_SK]
        ,[Vendor_SK]
        ,[Company_SK]
        ,[Sales_Organization_SK]
        ,[DocumentDatekey]
        ,[EntryDatekey]
        ,[Entry_TM]
        ,[Inventory_Management_Movement_Type_ID]
        ,[ETL_Reference_DT]
        ,[ETL_Batch_ID]
    )
	VALUES (
	  src.[Purchasing_Document_SK]
    , src.[Purchasing_Document_Item_ID]
    , src.[Account_Assignment_Sequential_ID]
    , src.[Purchase_Order_History_Transaction_Event_Type_ID]
    , src.[Material_Document_Year]
    , src.[Material_Document_SK]
    , src.[Material_Document_ID]
    , src.[Material_Document_Item_ID]
    , src.[PostingDatekey]
    , src.[Purchase_Order_History_Category_ID]
    , src.[FinalQuantity]
    , src.[FinalAmount]
    , src.[Material_SK]
    , src.[Plant_SK]
    , src.[Vendor_SK]
    , src.[Company_SK]
    , src.[Sales_Organization_SK]
    , src.[DocumentDatekey]
    , src.[EntryDatekey]
    , src.[Entry_TM]
    , src.[Inventory_Management_Movement_Type_ID]
    , src.[ETL_Reference_DT]
    , src.[ETL_Batch_ID]
	);
